@ChessPlatform.Backend_HostAddress = http://localhost:5133

POST {{ChessPlatform.Backend_HostAddress}}/register/
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "Pa$$w0rd"
}

###

GET {{ChessPlatform.Backend_HostAddress}}/game/1
Accept: application/json
